/**
 * Fotos, die Niklas besorgen muss (Schritt „Bilder“). Jeder Eintrag erscheint als klar markierter Bildplatzhalter mit
 * Motivbeschreibung (src/components/BildPlatzhalter.astro) – keine gezeichneten Ersatzgrafiken. Die Liste für Niklas entsteht
 * mit `node scripts/list-photos.mjs` (docs/fotoliste.md). Ein Foto ersetzen heißt: Datei nach public/images/welten/ legen
 * und den Platzhalter im Weltmodul durch ein <img> ersetzen; der Eintrag hier bekommt dann `status: 'da'`.
 *
 * ratio: Seitenverhältnis des Rahmens ('3-2', '4-3', '21-9', '4-5', '1-1', '16-9')
 */
export const FOTOS = {
  'w04-architektur': {
    welt: '04', ratio: '21-9', status: 'fehlt',
    titel: 'Architektur in Schwarzweiß',
    motiv: 'Treppenhaus oder Fassade eines älteren Geschäftshauses in der Oberpfalz, von unten gegen das Licht, strenge Linien. Schwarzweiß, hoher Kontrast, kein Mensch im Bild, keine lesbaren Schilder oder Firmennamen.',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 04, breiter Streifen unter dem Leitartikel; später Branchenseite Kanzlei',
    alt: 'Schwarzweißaufnahme einer Treppe in einem Geschäftshaus von unten gesehen',
    rechte: 'eigene Aufnahme oder lizenziert; Nutzungsrecht und Abbildungsrechte vorher klären',
  },
  'w04-dokumente': {
    welt: '04', ratio: '4-5', status: 'fehlt',
    titel: 'Dokumente und Schreibtisch',
    motiv: 'Nahaufnahme von Akten, Füller und einem aufgeschlagenen Gesetzbuch auf hellem Holz, Streiflicht von links. Schwarzweiß. Die Texte auf den Seiten dürfen nicht lesbar sein; keine Hände, keine Gesichter.',
    format: 'hoch 4:5, mindestens 1600 × 2000 px',
    einsatz: 'Welt 04, Marginalspalte neben dem Themenregister',
    alt: 'Schwarzweißaufnahme von Akten, Füller und aufgeschlagenem Buch auf einem Schreibtisch',
    rechte: 'eigene Aufnahme oder lizenziert; keine fremden Dokumente abbilden',
  },
  'w05-kopf': {
    welt: '05', ratio: '21-9', status: 'fehlt',
    titel: 'Gesamtansicht im Studio',
    motiv: 'Ein restaurierter Roadster, Baujahr um 1960, seitlich im Studio auf dunkelgrünem Hintergrund, weiches Streiflicht entlang der Karosserie, Chrom spiegelt die Lichtkante. Kein Kennzeichen, keine Personen, kein sichtbarer Herstellername.',
    format: 'sehr breit 21:9, mindestens 2560 × 1100 px',
    einsatz: 'Welt 05, Kopfbild unter dem Titel',
    alt: 'Restaurierter Oldtimer-Roadster im Studio vor dunkelgrünem Hintergrund',
    rechte: 'eigene Aufnahme; Fahrzeughalter und Abbildungsrechte vorher klären',
  },
  'w05-strecke-1': {
    welt: '05', ratio: '21-9', status: 'fehlt',
    titel: 'Querfahrt 01 · Front und Scheinwerfer',
    motiv: 'Frontpartie im Dreiviertelblick: runder Scheinwerfer, Chromstoßstange, Kühlergrill. Dunkelgrüner Studiohintergrund, Reflexe auf dem Lack. Kein Kennzeichen, kein Herstellername.',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 05, Bildstrecke der Querfahrt, Band 01',
    alt: 'Frontpartie eines Oldtimers mit rundem Scheinwerfer und Chromstoßstange',
    rechte: 'eigene Aufnahme oder lizenziert; Abbildungsrechte klären',
  },
  'w05-strecke-2': {
    welt: '05', ratio: '21-9', status: 'fehlt',
    titel: 'Querfahrt 02 · Emblem',
    motiv: 'Nahaufnahme eines Chromemblems oder einer Kühlerfigur, geringe Schärfentiefe, Lichtkante auf dem Chrom. Das Emblem darf keinem echten Hersteller gehören (neutrales oder eigenes Zeichen verwenden oder unkenntlich machen).',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 05, Bildstrecke der Querfahrt, Band 02',
    alt: 'Nahaufnahme eines verchromten Emblems auf grünem Lack',
    rechte: 'eigene Aufnahme; Markenrechte am Emblem beachten',
  },
  'w05-strecke-3': {
    welt: '05', ratio: '21-9', status: 'fehlt',
    titel: 'Querfahrt 03 · Tacho und Armaturenbrett',
    motiv: 'Rundinstrumente, Tacho mit elfenbeinfarbenem Zifferblatt, Chromringe, Holz oder Lack des Armaturenbretts. Warmes Licht, dunkles Umfeld. Keine lesbaren Herstellerlogos.',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 05, Bildstrecke der Querfahrt, Band 03',
    alt: 'Rundinstrumente und Tacho im Armaturenbrett eines Oldtimers',
    rechte: 'eigene Aufnahme; keine fremden Logos abbilden',
  },
  'w05-strecke-4': {
    welt: '05', ratio: '21-9', status: 'fehlt',
    titel: 'Querfahrt 04 · Ledernaht',
    motiv: 'Nahaufnahme einer handgenähten Naht an einem Ledersitz oder einer Türverkleidung, Kontrastgarn in Elfenbein, Streiflicht betont das Korn des Leders.',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 05, Bildstrecke der Querfahrt, Band 04',
    alt: 'Handgenähte Naht an einem Ledersitz mit elfenbeinfarbenem Garn',
    rechte: 'eigene Aufnahme; keine Personen im Bild',
  },
  'w05-vorher': {
    welt: '05', ratio: '16-9', status: 'fehlt',
    titel: 'Vorher: Fahrzeug vor der Restaurierung',
    motiv: 'Dasselbe Fahrzeug wie „Nachher“, vor der Arbeit: matter, stellenweise durchgerosteter Lack, Staub, ausgeblichene Chromteile. Gleicher Kamerastandpunkt und gleiche Brennweite wie das Nachher-Bild, Werkstatthalle als Hintergrund.',
    format: 'quer 16:9, mindestens 2000 × 1125 px, identischer Ausschnitt wie „Nachher“',
    einsatz: 'Welt 05, Vorher-Nachher-Schieber, linke Seite',
    alt: 'Oldtimer vor der Restaurierung mit mattem, rostigem Lack',
    rechte: 'eigene Aufnahme; Fahrzeughalter und Abbildungsrechte klären',
  },
  'w05-nachher': {
    welt: '05', ratio: '16-9', status: 'fehlt',
    titel: 'Nachher: Fahrzeug nach der Restaurierung',
    motiv: 'Dasselbe Fahrzeug wie „Vorher“ mit identischem Kamerastandpunkt: frischer grüner Lack, polierter Chrom, saubere Fugen. Gleicher Hintergrund (Werkstatthalle) wie beim Vorher-Bild.',
    format: 'quer 16:9, mindestens 2000 × 1125 px, identischer Ausschnitt wie „Vorher“',
    einsatz: 'Welt 05, Vorher-Nachher-Schieber, rechte Seite',
    alt: 'Derselbe Oldtimer nach der Restaurierung mit glänzendem grünem Lack',
    rechte: 'eigene Aufnahme; Fahrzeughalter und Abbildungsrechte klären',
  },
  'w07-makro': {
    welt: '07', ratio: '21-9', status: 'fehlt',
    titel: 'Makro: Metall und Laserlicht',
    motiv: 'Makroaufnahme einer frisch gefrästen Metalloberfläche mit feinen Fräsriefen, schräg von einer dünnen Laserlinie in Gelb oder Weiß gestreift. Kühl entwickelt, dunkler Hintergrund, keine Maschinenmarken, keine Personen.',
    format: 'sehr breit 21:9, mindestens 2400 × 1030 px',
    einsatz: 'Welt 07, Kopfbild und Hintergrund der Laserlinien-Szene',
    alt: 'Makroaufnahme einer gefrästen Metalloberfläche mit einer Laserlinie',
    rechte: 'eigene Aufnahme; keine Kundenbauteile mit erkennbarem Logo oder Kennzeichnung',
  },
  'w07-bauteil': {
    welt: '07', ratio: '4-3', status: 'fehlt',
    titel: 'Bauteil-Drehung: 12 Ansichten',
    motiv: 'Ein einziges, selbst gefertigtes Demo-Bauteil (z. B. ein Frästeil mit Bohrungen und Taschen) auf neutralem dunkelgrauem Drehteller, in 12 Aufnahmen im Abstand von 30 Grad (0° bis 330°), gleiche Kamerahöhe, gleiche Belichtung, Kantenlicht von links. Kühl, sichtbare Bearbeitungsspuren, keine Kundenzeichnung, kein Logo.',
    format: '12 Dateien quer 4:3, je mindestens 1600 × 1200 px, durchnummeriert (bauteil-00 bis bauteil-11)',
    einsatz: 'Welt 07, Bauteil drehen per Ziehen oder Scrollen (mobil mit 6 der 12 Ansichten)',
    alt: 'Gefrästes Bauteil auf einem Drehteller aus wechselnden Blickwinkeln',
    rechte: 'eigene Aufnahme eines selbst gefertigten Teils; nichts von Kunden abbilden',
  },
  'w01-brot-gross': {
    welt: '01', ratio: '4-3', status: 'fehlt',
    titel: 'Landbrot mit Schnitten',
    motiv: 'Ein rundes Landbrot mit dunkler Kruste und eingeschnittenem Muster, frisch aus dem Ofen, schräges Licht (Fensterlicht von links), Mehlstaub auf dem Holzbrett. Warm entwickelt, sichtbares Korn. Keine Personen, keine Stockfoto-Anmutung.',
    format: 'quer 4:3, mindestens 2400 × 1800 px (zugeschnitten wird in Laibform)',
    einsatz: 'Welt 01, großes Bild neben dem Titel; später Branchenseite Bäckerei',
    alt: 'Rundes Landbrot mit dunkler Kruste und eingeschnittenem Muster auf einem Holzbrett',
    rechte: 'eigene Aufnahme aus der Backstube; Rechte an Brettern, Etiketten und Hintergrund klären',
  },
  'w01-brot-klein': {
    welt: '01', ratio: '4-3', status: 'fehlt',
    titel: 'Roggenlaib mit Krume',
    motiv: 'Ein ovaler Roggenlaib, angeschnitten, die Krume im Gegenlicht sichtbar, Mehlstaub in der Luft. Makroaufnahme mit geringer Schärfentiefe, warm entwickelt.',
    format: 'quer 4:3, mindestens 1800 × 1350 px',
    einsatz: 'Welt 01, kleines Bild links unten überlappend',
    alt: 'Angeschnittener Roggenlaib mit offener Krume im Gegenlicht',
    rechte: 'eigene Aufnahme aus der Backstube',
  },
  'w08-raum': {
    welt: '08', ratio: '3-2', status: 'fehlt',
    titel: 'Heller Behandlungsraum',
    motiv: 'Ein heller, aufgeräumter Behandlungsraum mit Liege, großem Fenster und Blick ins Grüne oder aufs Wasser, weiches Tageslicht, helle Holz- und Mintfarben. Keine Personen, keine lesbaren Schilder.',
    format: 'quer 3:2, mindestens 2400 × 1600 px',
    einsatz: 'Welt 08, Bild neben den Behandlungskarten',
    alt: 'Heller Behandlungsraum mit Liege und großem Fenster',
    rechte: 'eigene Aufnahme in den eigenen Räumen; keine Personen im Bild',
  },
  'w08-haende': {
    welt: '08', ratio: '4-5', status: 'fehlt',
    titel: 'Hände bei der Behandlung',
    motiv: 'Zwei Hände bei einer Behandlung an Schulter oder Rücken, Ausschnitt ohne erkennbares Gesicht und ohne Tätowierungen, helles Licht, ruhige Farben. Nur mit schriftlicher Einwilligung der abgebildeten Personen.',
    format: 'hoch 4:5, mindestens 1600 × 2000 px',
    einsatz: 'Welt 08, neben dem Buchungsmodul oder den Behandlungskarten',
    alt: 'Hände bei einer Behandlung am Rücken, ohne Gesicht',
    rechte: 'Einwilligung der abgebildeten Personen schriftlich einholen; keine Stockfotos mit unklaren Rechten',
  },
  'w08-weiher': {
    welt: '08', ratio: '21-9', status: 'fehlt',
    titel: 'Der Weiher',
    motiv: 'Eine ruhige Wasserfläche bei Tageslicht, Schilf am Rand, flaches Licht, dahinter Bäume. Aufnahmeort muss frei zugänglich sein oder die Erlaubnis liegt vor. Dasselbe Motiv wie das Foto „See in der Abenddämmerung“ aus Welt 09, gleicher Standpunkt.',
    format: 'sehr breit 21:9, mindestens 2560 × 1100 px, identischer Standpunkt wie „See am Abend“',
    einsatz: 'Welt 08, Abschluss der Welt und Anfang des Übergangs zum See',
    alt: 'Ruhiger Weiher mit Schilf bei Tageslicht',
    rechte: 'eigene Aufnahme; Aufnahmeort und Eigentümer klären',
  },
  'w09-see-abend': {
    welt: '09', ratio: '16-9', status: 'fehlt',
    titel: 'See am Abend',
    motiv: 'Ein See am frühen Abend, tiefstehende Sonne, warmes Licht auf dem Wasser, Schilf und Steg im Vordergrund. Dasselbe Motiv wie das Foto „Weiher“ aus Welt 08, gleicher Standpunkt. Natürliches Licht, nicht stark bearbeitet.',
    format: 'quer 16:9, mindestens 2560 × 1440 px, identischer Standpunkt wie „Weiher“',
    einsatz: 'Welt 09, Vollbild am Anfang der Welt und erstes Bild der Tageszeit-Überblendung',
    alt: 'Ein See am frühen Abend mit warmem Licht auf dem Wasser',
    rechte: 'eigene Aufnahme; Aufnahmeort und Eigentümer klären',
  },
  'w09-see-daemmerung': {
    welt: '09', ratio: '16-9', status: 'fehlt',
    titel: 'See in der Dämmerung',
    motiv: 'Derselbe Standpunkt wie „See am Abend“, 30 bis 40 Minuten später: Himmel violett und rosa, Wasser spiegelt, erste Lichter am Ufer. Ohne Personen.',
    format: 'quer 16:9, mindestens 2560 × 1440 px, identischer Standpunkt',
    einsatz: 'Welt 09, zweites Bild der Tageszeit-Überblendung',
    alt: 'Derselbe See in der Dämmerung mit violettem Himmel',
    rechte: 'eigene Aufnahme, gleicher Standpunkt wie das Abendbild',
  },
  'w09-see-nacht': {
    welt: '09', ratio: '16-9', status: 'fehlt',
    titel: 'See bei Nacht',
    motiv: 'Derselbe Standpunkt, blaue Stunde bis Nacht: dunkles Wasser, ein erleuchtetes Fenster am Haus gegenüber oder am Steg. Ohne Personen.',
    format: 'quer 16:9, mindestens 2560 × 1440 px, identischer Standpunkt (Stativ, Langzeitbelichtung)',
    einsatz: 'Welt 09, drittes Bild der Tageszeit-Überblendung',
    alt: 'Derselbe See bei Nacht mit einem erleuchteten Fenster',
    rechte: 'eigene Aufnahme, gleicher Standpunkt wie das Abendbild',
  },
  'w09-zimmer': {
    welt: '09', ratio: '3-2', status: 'fehlt',
    titel: 'Zimmer mit Fensterblick',
    motiv: 'Ein Gästezimmer mit Fensterblick auf den See, Leinenbettwäsche, Holzboden, natürliches Abendlicht. Keine Personen, keine Logos auf Textilien.',
    format: 'quer 3:2, mindestens 2400 × 1600 px',
    einsatz: 'Welt 09, neben den Zimmerkarten',
    alt: 'Gästezimmer mit großem Fenster und Blick auf einen See',
    rechte: 'eigene Aufnahme im eigenen Haus; keine Personen',
  },
  'w09-teller': {
    welt: '09', ratio: '1-1', status: 'fehlt',
    titel: 'Tellerdetail',
    motiv: 'Nahaufnahme eines angerichteten Tellers (z. B. Fisch mit Gemüse) auf Holztisch, geringe Schärfentiefe, warmes Kerzenlicht. Keine Personen, kein Besteck mit Logo.',
    format: 'quadratisch 1:1, mindestens 1800 × 1800 px',
    einsatz: 'Welt 09, neben der Speisekarte',
    alt: 'Nahaufnahme eines angerichteten Tellers bei Kerzenlicht',
    rechte: 'eigene Aufnahme aus der eigenen Küche',
  },
};
